apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: lab-pool
      protocol: layer2
      avoid-buggy-ips: true
      addresses:
      - 192.168.40.32/27
